export type AppEnv = {
  PORT: number;
  MONGODB_URI: string;
  NODE_ENV: string;
  JWT_ACCESS_SECRET: string;
  JWT_REFRESH_SECRET: string;
  ACCESS_TOKEN_TTL: string;
  REFRESH_TOKEN_TTL: string;
  REFRESH_COOKIE_NAME: string;
  MISTRAL_API_KEY: string;
  BREVO_API_KEY: string;
  SMTP_HOST: string;
  SMTP_PORT: number;
  SMTP_USER: string;
  SMTP_PASS: string;
  MAIL_FROM: string;
  LOGGER_LEVEL: string;
  SEND_MAIL: boolean;
  EMAIL_VERIFICATION: boolean;
};
